server:
  port: 8081

spring:
  application:
    name: chat-api
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # Quan trọng: Bật lên để Consumer có thể biết được Class nào để mapping
        spring.json.add.type.headers: true