server:
    port: 8080

spring:
    application:
        name: chat-ws-gateway
    data:
        redis:
            host: localhost
            port: 6379
    kafka:
        bootstrap-servers: localhost:9092
        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
            properties:
                spring.json.add.type.headers: true

jwt:
    secret: "your-very-long-secret-key-at-least-32-chars-here"

logging:
    level:
        com.app.chat_ws_gateway: DEBUG